### ISSUE TITLE
github link in npm is invalid

### ISSUE THREAD

**Issue by nlynzaad** [Nadrama-com/remix-webcrypto-cookie-session#1]
Hi,

Came across this package in the remix encrypted cookie [discussion](https://github.com/remix-run/remix/discussions/5209), noticed on npm the  github link is invalid see below screenshot.

![image](https://github.com/user-attachments/assets/ffd13400-57f0-4292-9575-4f73ef3c7c02)

**Comment by ryan0x44** [comment]
Hey @nlynzaad thanks for reporting this! Should be all fixed now :)
